# TERM = "alacritty"
import = ["/home/javier/.config/alacritty/dracula.toml"]

[font]
size = 11.0
# style = "Regular"

[font.normal]
family = "CaskaydiaCove NF"

[shell]
program = "/bin/zsh"

[window]
opacity = 0.7
